Homework23 attempt2
Without the try/catch in BaseTest for:

public String getDeletedPlaylistMsg() {
        notificationMsg = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.success.show")));
        return notificationMsg.getText();

I get the following error in the report:
java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.support.ui.WebDriverWait.until(java.util.function.Function)" because "this.wait" is null

With the try/catch in BaseTest for:

public String getDeletedPlaylistMsg() {
    try {
        notificationMsg = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.success.show")));
    } catch (NullPointerException npe) {
        //return notificationMsg.getText();
    }
    return notificationMsg.getText();

I get the following error in the report:

java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.getText()" because "this.notificationMsg" is null